# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.topic.name=message-stream
kafka.consumer.group.id=spark-consumer-group

# Spark Configuration
spark.app.name=KafkaSparkStreaming
spark.master=local[*]
spark.sql.shuffle.partitions=2

# Streaming Configuration
spark.streaming.batch.duration=5
spark.streaming.backpressure.enabled=true

# Logging
spark.log.level=WARN
